"""empty message

Revision ID: 302458711937
Revises: e95be277b8e8
Create Date: 2021-11-29 17:04:31.706218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302458711937'
down_revision = 'e95be277b8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liketable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('postalcode', sa.String(length=120), nullable=False),
    sa.Column('about', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userliketable',
    sa.Column('User', sa.Integer(), nullable=False),
    sa.Column('LikeTable', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LikeTable'], ['liketable.id'], ),
    sa.ForeignKeyConstraint(['User'], ['user.id'], ),
    sa.PrimaryKeyConstraint('User', 'LikeTable')
    )
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('todolist', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('userliketable')
    op.drop_table('liketable')
    # ### end Alembic commands ###
