"""empty message

Revision ID: b4a023c45a5a
Revises: 830fdde37f24
Create Date: 2021-11-19 16:03:37.015686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a023c45a5a'
down_revision = '830fdde37f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'info', type_='foreignkey')
    op.drop_column('info', 'user_id')
    # ### end Alembic commands ###
