"""empty message

Revision ID: e95be277b8e8
Revises: 960fc2884858
Create Date: 2021-11-24 13:28:57.480117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95be277b8e8'
down_revision = '960fc2884858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendstatus', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendstatus', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
