"""empty message

Revision ID: ec882db1a7bb
Revises: 302458711937
Create Date: 2021-11-29 18:48:44.183411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec882db1a7bb'
down_revision = '302458711937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liketable', sa.Column('like_books', sa.String(length=120), nullable=True))
    op.add_column('liketable', sa.Column('like_movies', sa.String(length=120), nullable=False))
    op.drop_constraint('liketable_user_id_fkey', 'liketable', type_='foreignkey')
    op.drop_column('liketable', 'user_id')
    op.drop_column('liketable', 'postalcode')
    op.drop_column('liketable', 'address')
    op.drop_column('liketable', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liketable', sa.Column('about', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('liketable', sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('liketable', sa.Column('postalcode', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('liketable', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('liketable_user_id_fkey', 'liketable', 'user', ['user_id'], ['id'])
    op.drop_column('liketable', 'like_movies')
    op.drop_column('liketable', 'like_books')
    # ### end Alembic commands ###
